//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MooiKind
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MooiKindEntities : DbContext
    {
        public MooiKindEntities()
            : base("name=MooiKindEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Description> Descriptions { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Name> Names { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
    }
}
